version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: maxxidata-api
    container_name: maxxidata-api
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    ports:
      - "${PORT}:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - maxxidata-network
    command: npm run start

  db:
    image: postgres:12.6-alpine
    container_name: 'db'
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - maxxidata-network

networks:
  maxxidata-network:
    driver: bridge

volumes:
  node_modules: