version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-poc
    container_name: app-poc
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - app-network
    command: npm run start:dev

  db:
    image: postgres:12.6-alpine
    container_name: 'db'
    restart: always
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "root"
      POSTGRES_DB: "maxxidata_dev"
    ports:
      - "5433:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - app-network
  networks:
    app-network:
      driver: bridge

  volumes:
    node_modules: