version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-poc
    container_name: app-poc
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - app-network
    command: npm run start:dev
  networks:
    app-network:
      driver: bridge

  volumes:
    node_modules: